name: build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install dependencies
      run: |
        sudo apt-get -y install libxml2-utils rpm
    - name: Initialize Graylog
      run: |
        export GRAYLOG_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="parent"]/*[local-name()="version"]/text()' pom.xml)
        echo "Checking out Graylog ${GRAYLOG_VERSION}"
        git clone --depth 1 --branch "${GRAYLOG_VERSION}" https://github.com/Graylog2/graylog2-server.git ../graylog2-server
        pushd ../graylog2-server
        mvn generate-resources -pl graylog2-server -B -V
        popd
    - name: Build
      run: mvn -B package --file pom.xml

