name: pr_build

on:
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Install dependencies
      run: |
        sudo apt-get -y install libxml2-utils rpm
    - name: Graylog version
      id: vinfo
      run: |
        export GRAYLOG_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="parent"]/*[local-name()="version"]/text()' pom.xml)
        echo "Building for Graylog ${GRAYLOG_VERSION}"
        echo "GRAYLOG_VERSION=${GRAYLOG_VERSION}" >> $GITHUB_ENV
        echo "::set-output name=GRAYLOG_VERSION::$GRAYLOG_VERSION"
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
    - uses: actions/cache@v3
      id: cache
      with:
        path: ../graylog2-server
        key: ${{ runner.os }}-${{ steps.vinfo.outputs.date }}-${{ steps.vinfo.outputs.GRAYLOG_VERSION }}
    - name: Initialize Graylog
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        echo "Checking out Graylog ${{ env.GRAYLOG_VERSION }}"
        git clone --depth 1 --branch "${{ env.GRAYLOG_VERSION }}" https://github.com/Graylog2/graylog2-server.git ../graylog2-server
        pushd ../graylog2-server
        ./mvnw compile
        popd
    - name: Build
      run: mvn -B package --file pom.xml
